### ISSUE TITLE
[TRACKING] KDE packages that need and update file

### ISSUE THREAD

**Issue by yopito** [void-linux/void-packages#1110]
If PR #1109 gets merged, some KDE package needs an `update` file  to find their (distfile) update
(content like "`pkgname=${pkgname%5}`"):

- [ ] baloo-widgets5
- [ ] kfilemetadata5
- [ ] libkipi5
- [ ] bluez-qt5
- [ ] baloo5
- [ ] kate5
- [ ] oxygen-gtk+
- [ ] phonon-qt5-backend-gstreamer
- [ ] kactivities5
- [ ] marble5
- [ ] phonon-qt5-backend-vlc
- [ ] okteta5
- [ ] kactivities5-stats
- [ ] networkmanager-qt5
- [ ] libkexiv25
- [ ] kdeplasma-addons5
- [ ] kde-gtk-config5
- [ ] phonon-qt5
- [ ] oxygen-gtk+3
- [ ] modemmanager-qt5

**Comment by yopito** [comment]
all fixed in PR #1109 : close this tracking
