### ISSUE TITLE
Tracking: always enable gir (and vala)

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#11378]
Now that gir (and vala) works for cross builds, all packages should always enable the corresponding build_option by default. This also requires adding `build_helper="gir"` to the template and sometimes adding `vala` to the makedepends like `$(vopt_if gir vala)`. Also revbump the package for rebuild.

Here's a hopefully complete list of packages which as of now have conditional enabling:
- [x] GConf
- [x] ModemManager
- [x] NetworkManager
- [x] PackageKit
- [x] atril
- [x] avahi-discover
- [x] caja
- [x] cheese (seems it was built? consider revbump)
- [x] clutter-gst
- [x] colord-gtk
- [x] evolution-data-server
- [x] evolution
- [x] farstream
- [x] folks (depends on evolution-data-server)
- [x] gmime
- [x] gnome-autoar
- [x] gnome-online-miners
- [x] gom
- [x] gst-plugins-bad1
- [x] gupnp-igd
- [ ] ibus-anthy ; anthy-devel cannot be cross compiled
- [x] libcryptui
- [x] libdbusmenu-glib
- [x] libgepub
- [x] libgsf
- [x] libkeybinder2
- [x] libkeybinder3
- [x] libmatekbd
- [x] libmirage
- [x] libostree
- [x] libwnck
- [x] libwnck2
- [ ] liferea
- [x] lightdm
- [x] mash
- [x] mate-menus
- [x] mate-panel
- [ ] nautilus-sendto
- [ ] rhythmbox
- [x] telepathy-farstream
- [x] telepathy-logger
- [x] upower
- [x] vte290
- [x] xreader

I'll be going through the list  enabling gir and testing cross builds. If you find time, you may want help.

**Comment by pullmoll** [comment]
The package `uhttpmock` is failing when trying to cross build it, yet it is required for `evolution-data-server`. Any help is appreciated.

**Comment by jnbr** [comment]
When cross building, something pulls in `gobject-introspection` for the target and `httpmock` detects it: `checking for gobject-introspection... yes`.
So it should either use the gir build helper or disable it.

**Comment by pullmoll** [comment]
Yeah, I know that and already tried to use `build_helper="gir"`, but it fails finding a shared object which is built into `${wrksrc}/libhttpmock/.libs`. The `gobject-introspection` file `qemu-g-ir-scanner-qemuwrapper` however sets up `LD_LIBRARY_PATH` to look for `.libs` but not `*/.libs`. I don't know if wildcards would be expanded work there but I'll give it a try. But then there could be `*/*/.libs` in other packages or even deeper in the hierarchy.

**Comment by pullmoll** [comment]
Ok, I found a solution for `uhttpmock`:

+ Make `gobject-introspection` file `g-ir-scanner-qemuwrapper` respect a previously defined `$LD_LIBRARY_PATH`, i.e. append it, if it's not empty.
+ Add `build_helper="gir"` to `uhttpmock/template`
+ Add `export LD_LIBRARY_PATH=${wrksrc}/libuhttpmock/.libs` in the template's `pre_build()` stage.

Now the cross environment knows where to also look for shared libraries and the build succeeds.

**Comment by pullmoll** [comment]
There is something wrong with `aarch64-musl` libs `gpg` or perhaps `libgpg-error`.
Many `build_helper="gir"` packages using one or the other print an error:
```
gpgrt fatal: sizeof lock obj
```
and make `g-ir-scanner` emit signal 6 (SIGABRT) and dump core.
Right now I'm marking them as broken to avoid them blocking the build queue but of course an idea where to look for the underlying problem and a fix would be preferred.

**Comment by q66** [comment]
Sure looks like a qemu bug to me

**Comment by pullmoll** [comment]
It also happens for `ppc64-musl` trying to build `gcr` here, so it's definitely `musl` and not our `aarch64-musl` builder. Perhaps you can try to cross build `gcr` from `ppc64le` to `ppc64le-musl` and see if it happens there as well @q66 ?

**Comment by pullmoll** [comment]
Heh, the `post_configure()` in `libgpg-error/template` is most probably the culprit. Using the `lock-obj-pub-arm.h` for all cross architectures is probably a bad idea.

**Comment by q66** [comment]
why not just pre-generate the files for the archs we have?

**Comment by pullmoll** [comment]
Hmm.. would that be easier? You still need to cross compile `src/gen-posix-lock-obj.c` for each arch and run it under that arch to get the results.

**Comment by q66** [comment]
well, could pre-generate it in qemu... it's probably better than depending on qemu

but yeah, the header generated here is quite different

```
## lock-obj-pub.powerpc64le-unknown-linux-gnu.h
## File created by gen-posix-lock-obj - DO NOT EDIT
## To be included by mkheader into gpg-error.h

typedef struct
{
  long _vers;
  union {
    volatile char _priv[40];
    long _x_align;
    long *_xp_align;
  } u;
} gpgrt_lock_t;

#define GPGRT_LOCK_INITIALIZER {1,{{0,0,0,0,0,0,0,0, \
                                    0,0,0,0,0,0,0,0, \
                                    0,0,0,0,0,0,0,0, \
                                    0,0,0,0,0,0,0,0, \
                                    0,0,0,0,0,0,0,0}}}
##
## Local Variables:
## mode: c
## buffer-read-only: t
## End:
##
```

note how `_priv` is has size `40` rather than `24`...

**Comment by q66** [comment]
but yeah, now i'm almost 100% certain that this is the issue...

**Comment by pullmoll** [comment]
This seems to work in `libgpg-error/template`:
```
if [ "$CROSS_BUILD" ]; then
        hostmakedepends="qemu-user-static"
fi

post_configure() {
        if [ "$CROSS_BUILD" ]; then
                $CC -DHOST_TRIPLET_STRING='"${XBPS_CROSS_TRIPLET}"' \
                        -o gen-posix-lock-obj \
                        src/gen-posix-lock-obj.c
                qemu-${XBPS_TARGET_QEMU_MACHINE}-static \
                        -L ${XBPS_CROSS_BASE} \
                        gen-posix-lock-obj \
                        > src/syscfg/lock-obj-pub.${XBPS_CROSS_TRIPLET#*-}.h
        fi
}
```

**Comment by pullmoll** [comment]
But compiling just `libgpg-error` and trying to build `gcr` for `ppc64-musl` still fails. Perhaps also `libgcrypt` and/or other packages using `libgpg-error` need to be rebuilt.

**Comment by pullmoll** [comment]
The `-DHOST_TRIPLET_STRING=…` is wrong. It needs to be quoted but expanded from `${XBPS_CROSS_TRIPLET#*-}`...

**Comment by pullmoll** [comment]
This one looks as if it generates a correct header file:
```
if [ "$CROSS_BUILD" ]; then
        hostmakedepends="qemu-user-static"
fi

post_configure() {
        if [ "$CROSS_BUILD" ]; then
                $CC -DHAVE_CONFIG_H -I. -pthread -o gen-posix-lock-obj src/gen-posix-lock-obj.c
                qemu-${XBPS_TARGET_QEMU_MACHINE}-static \
                        -L ${XBPS_CROSS_BASE} \
                        gen-posix-lock-obj \
                        > src/syscfg/lock-obj-pub.${XBPS_CROSS_TRIPLET#*-}.h
                msg_normal "Generated lobck-obj-pub.${XBPS_CROSS_TRIPLET}.h ...\n"
                cat src/syscfg/lock-obj-pub.${XBPS_CROSS_TRIPLET#*-}.h
        fi
}

```

**Comment by q66** [comment]
LGTM :shipit:

**Comment by pullmoll** [comment]
So libgpg-error had an error which I hope is history with https://github.com/void-linux/void-packages/commit/96d599c51b5073d457da4f4b02577b0b83a484f0

**Comment by q66** [comment]
cool, i guess that means all the `broken=`s can now be removed :)

**Comment by pullmoll** [comment]
I'll revbump all packages which have `libgpg-error-devel` to be sure.

**Comment by pullmoll** [comment]
Trying to cross build `gjs` for `ppc64-musl` I see a `qemu-user-static` trap 5 (SIGTRAP) and the following error message:
```
  GICOMP   Regress-1.0.gir
  GICOMP   GIMarshallingTests-1.0.gir

(process:16363): Gjs-ERROR **: 15:42:58.619: Could not initialize Javascript
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
/usr/bin/g-ir-scanner-qemuwrapper: line 9: 16363 Trace/breakpoint trap   /usr/bin/qemu-${XBPS_TARGET_QEMU_MACHINE}-static -L ${XBPS_CROSS_BASE} -E LD_LIBRARY_PATH="${XBPS_CROSS_BASE}/usr/lib:.libs:${GIR_EXTRA_LIBS_PATH}" "$@"
Command '['/usr/bin/g-ir-scanner-qemuwrapper', '/builddir/gjs-1.56.1/tmp-introspectgibots59/.libs/GjsPrivate-1.0', '--introspect-dump=/builddir/gjs-1.56.1/tmp-introspectgibots59/functions.txt,/builddir/gjs-1.56.1/tmp-introspectgibots59/dump.xml']' returned non-zero exit status 133.
make[1]: *** [/usr/share/gobject-introspection-1.0/Makefile.introspection:156: GjsPrivate-1.0.gir] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/builddir/gjs-1.56.1'
make: *** [Makefile:1573: all] Error 2
=> ERROR: gjs-1.56.1_2: do_build: '${make_cmd} ${makejobs} ${make_build_args} ${make_build_target}' exited with 2
=> ERROR:   in do_build() at common/build-style/gnu-configure.sh:13
```
So it looks as if `mozjs60` for `ppc64-musl` has a problem - perhaps similar to `libgpg-error` - with its initialization or the binding between `gjs` and `mozjs60` is somehow borked.
Finding the cause for this may also be helpful for fixing `mozjs52` for `ppc*`.

**Comment by q66** [comment]
Hm, `--host` in autotools is the machine it will run for, `--target` is the machine it will create results for (this applies to e.g. compilers, for most things `--host` and `--target` are the same, `--build` is the actual host machine). That would make the configure in `mozjs60` completely wrong. Maybe try changing that

**Comment by pullmoll** [comment]
Tried to make it like `mozjs52`, i.e. just set `--target=$XBPS_CROSS_TRIPLET` for cross.
I think we can't set `--host` because a binary (ns_install) is built for the host and used to install the resulting files in the (temporary) destdir.
This change didn't fix the qemu trap, though.

**Comment by q66** [comment]
Well, that binary should respect `--build`, not `--host`...

**Comment by pullmoll** [comment]
Ok, back to the subject now that `webkit2gtk` was built with `gir` enabled for all targets.

Next I was trying to build `evolution-data-server` also with *gir everywhere* but first, the current version won't compile because of a problem with `ical`. The update `3.32.2` builds until it fails to link the `test-cal-client` stuff for introspection.

To be more specific it fails to link against the just built `${wrksrc}/build/src/private/libedbus-private.so` even when I specified that path as `export GIR_EXTRA_LIBS_PATH=${wrksrc}/build/src/private` in a `pre_build()` function.
The error happens when this command is run:
```
Scanning dependencies of target test-cal-client-get-view
g-ir-scanner: link: /builddir/.xbps-evolution-data-server/wrappers/arm-linux-musleabihf-gcc -o /builddir/evolution-data-server-3.32.2/build/src/libedataserver/tmp-introspectcigmxjba/EDataServer-1.2 -fstack-clash-protection -D_FORTIFY_SOURCE=2 -O2 -pipe -march=armv6 -mfpu=vfp -mfloat-abi=hard -g -I/usr/arm-linux-musleabihf/usr/include /builddir/evolution-data-server-3.32.2/build/src/libedataserver/tmp-introspectcigmxjba/EDataServer-1.2.o -L. -Wl,-rpath,. -Wl,--no-as-needed -L/builddir/evolution-data-server-3.32.2/build -Wl,-rpath,/builddir/evolution-data-server-3.32.2/build -L/builddir/evolution-data-server-3.32.2/build/src -Wl,-rpath,/builddir/evolution-data-server-3.32.2/build/src -L/builddir/evolution-data-server-3.32.2/build/src/libedataserver -Wl,-rpath,/builddir/evolution-data-server-3.32.2/build/src/libedataserver -L/builddir/evolution-data-server-3.32.2/build/src/private -Wl,-rpath,/builddir/evolution-data-server-3.32.2/build/src/private -L/builddir/evolution-data-server-3.32.2/build/src/camel -Wl,-rpath,/builddir/evolution-data-server-3.32.2/build/src/camel -L/usr/lib -Wl,-rpath,/usr/lib -L/usr/arm-linux-musleabihf/usr/lib -Wl,-rpath,/usr/arm-linux-musleabihf/usr/lib -lcamel-1.2 -ledataserver-1.2 -lgio-2.0 -lgobject-2.0 -Wl,--export-dynamic -pthread -lgmodule-2.0 -lglib-2.0
```
and reads
```
…
/usr/lib/gcc/arm-linux-musleabihf/9.1.0/../../../../arm-linux-musleabihf/bin/ld: warning: libedbus-private.so, needed by ./libedataserver-1.2.so, not found (try using -rpath or -rpath-link)
/usr/lib/gcc/arm-linux-musleabihf/9.1.0/../../../../arm-linux-musleabihf/bin/ld: ./libedataserver-1.2.so: undefined reference to `e_dbus_object_get_source_remote_creatable'
```
the fun part is there **is** a `-Wl,-rpath,.../build/src/private` where that private shlib can be found.

I currently have no clue what's going on there and would like to ask @Gottox or someone with more insight into that package for help.

Meanwhile I'll try to take care of above packages pending because `webkit2gtk` was the show stopper.

**Comment by q66** [comment]
Think you could enable `gst-plugins-bad1`? We have that stuff in both base gstreamer and the other plugins, I think it was just overlooked.

**Comment by pullmoll** [comment]
The list in the first comment was created by searching for `build_options+=" gir"` and I certainly missed some packages, yes. You're welcome create PRs for packages that can now be built with `build_helper="gir"`.

I'm away for some time now and will look later or tomorrow.

**Comment by sgn** [comment]
- `rhytmbox` is fixed,
- `nautilus-sendto` doesn't have anything to do with gir (for current version), I removed build options.

**Comment by pullmoll** [comment]
AFAICT this is done.
