### ISSUE TITLE
[Tracking] linux 5.1 dkms status

### ISSUE THREAD

**Issue by Hoshpak** [void-linux/void-packages#11660]
These dkms modules are important and their compatibility with a kernel version is relevant for the decision to move the default kernel version:

- [x] nvidia
- [x] nvidia390 (compilation and runtime tested)
- [x] nvidia340 (compilation and runtime tested)
- [x] zfs (officially supported with 0.8.0)
- [x] virtualbox-ose (compilation and runtime tested)

If you are using any of these modules, please consider contributing to this issue by installing `linux5.1` and `linux5.1-headers` and report if everything still works for you.

**Comment by steinex** [comment]
nvidia is working.

**Comment by pullmoll** [comment]
I successfully tested `rtl8812au-dkms` after adding `srcpkgs/rtl8812au/patches/kernel5.1-compat.patch`:

```
Description: define a macro for former function get_ds()
Author: @pullmoll
Origin: https://github.com/gordboy/rtl8812au/commit/ac063a4b1a87855e10f6cd1f358aaccbeee9b9c1

--- os_dep/osdep_service.c      2019-03-27 20:27:47.000000000 +0100
+++ os_dep/osdep_service.c      2019-05-09 07:49:01.296002221 +0200
@@ -32,6 +32,10 @@
 #endif
 #endif /* DBG_MEMORY_LEAK */

+/* For kernels >= 5.1.0 define get_ds() for backward compatibility */
+#if (LINUX_VERSION_CODE >= KERNEL_VERSION(5, 1, 0))
+  #define get_ds() (KERNEL_DS)
+#endif

 #if defined(PLATFORM_LINUX)
 /*
```

**Comment by abenson** [comment]
nvidia390 requires a patch, working on getting it working right now.

**Comment by zdykstra** [comment]
ZoL 0.8.0 has been tagged / released upstream - https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.8.0

**Comment by Vaelatern** [comment]
ZFS in PR, needs cross build fix.

**Comment by maop** [comment]
nvidia390 fails

```
linux5.1-5.1.8_1: configuring ...
Executing post-install kernel hook: 10-dkms ...
Available DKMS module: nvidia-390.116.
Available DKMS module: rtl8192eu-1.0.
Building DKMS module: nvidia-390.116... FAILED!
...
```
if you need the make log let me know... regards!

**Comment by abenson** [comment]
@maop [This patch works for x86_64](https://git.archlinux.org/svntogit/packages.git/plain/trunk/kernel-5.1.patch?h=packages/nvidia-390xx). No patch for i686 yet.

**Comment by abenson** [comment]
> No patch for i686 yet.

It has to be a conditional patch.

> kernel-5.1.patch cannot be applied, because the x86 source does not have the files which need patching 

When I tried it failed.

**Comment by Hoshpak** [comment]
Uvm is not part of the i686 driver so we just don't need that patch there. I updated the package to conditionally patch what's needed. I verified that it compiles on both architectures and would ask for some runtime testing.

**Comment by yilmzfurkan** [comment]
@Hoshpak Thanks. I have updated a few hours ago everything works fine. If I see some odd behavior I will report back.

**Comment by Hoshpak** [comment]
5.1 reached EOL.
