### ISSUE TITLE
[Tracking] libressl rebuild

### ISSUE THREAD

**Issue by jnbr** [void-linux/void-packages#12425]
Packages to be rebuilt (ordered by `xbps-sort-dependencies`)
Commits for bumps and some patches [here](https://github.com/void-linux/void-packages/pull/11754).

- [x] libevent
- [x] libssh2
- [x] nghttp2
- [x] curl
- [x] python
- [x] git
- [x] mysql
- [x] openldap
- [x] postgresql
- [x] ldns
- [x] pulseaudio
- [x] ruby
- [x] libgit2
- [x] python3
- [x] libnice
- [x] neon
- [x] rtmpdump
- [x] apr-util
- [x] iputils
- [x] openssh
- [x] postfix
- [x] qt5
- [x] unbound
- [x] cargo
- [x] libarchive
- [x] mit-krb5
- [x] gsoap
- [x] libwebsockets
- [x] trousers
- [x] libssh
- [x] grpc
- [x] wget
- [x] munge
- [x] sqlcipher
- [x] freerdp
- [x] spice-gtk
- [x] qt
- [x] lua51-luasec
- [x] gst-plugins-bad1
- [x] apache
- [x] libzip
- [x] net-snmp
- [x] pkcs11-helper
- [x] monitoring-plugins
- [x] w3m
- [x] Ice
- [x] monero
- [x] podofo
- [x] elinks
- [x] erlang
- [x] mariadb
- [x] libesmtp
- [x] libetpan
- [x] bind
- [x] re
- [x] rhash
- [x] zou
- [x] zola
- [x] znc
- [x] zchunk
- [x] zbackup
- [x] ympd
- [x] ykpivmgr
- [x] yara
- [x] xca
- [x] xbps
- [x] xarcan
- [x] xar
- [x] x11vnc
- [x] wvstreams
- [x] wrk
- [x] wpa_supplicant
- [x] wesnoth
- [x] watchman
- [x] warzone2100
- [x] vsftpd
- [x] vpn-ws
- [x] virtuoso
- [x] virtualbox-ose
- [x] vde2
- [x] vboot-utils
- [x] vanitygen
- [x] umurmur
- [x] uget
- [x] uftp
- [x] ucspi-ssl
- [x] tvheadend
- [x] ttyd
- [x] transmission
- [x] tpm-tools
- [x] tor
- [x] tnftp
- [x] tmplgen
- [x] tlsdate
- [x] tinc
- [x] thrift
- [x] thc-hydra
- [x] telepathy-salut
- [x] telegram-desktop
- [x] tectonic
- [x] tealdeer
- [x] tcpflow
- [x] tcpdump
- [x] taizen
- [x] sysdig
- [x] synergy
- [x] sylpheed
- [x] swiften
- [x] swi-prolog
- [x] supertuxkart
- [x] stunnel
- [x] stremio-shell
- [x] squid
- [x] spiped
- [x] spice
- [x] socat
- [x] slurm-wlm
- [x] slrn
- [x] sitecopy
- [x] sgfutils
- [x] serf
- [x] seafile-libclient
- [x] scrypt
- [x] sbsigntool
- [x] s6-networking
- [x] s3fs-fuse
- [x] s-nail
- [x] rustup
- [x] rust-sccache
- [x] rust-cargo-audit
- [x] rspamd
- [x] rooster
- [x] rng-tools
- [x] retroshare
- [x] remmina
- [x] rdis-git
- [x] rdesktop
- [x] rdedup
- [x] qupzilla1
- [x] qingy
- [x] qca-qt5
- [x] qca
- [x] python-curl
- [x] python-cryptography
- [x] python-M2Crypto
- [x] prosody
- [x] ppp
- [x] poco
- [x] pjproject
- [x] pijul
- [x] pidgin-sipe
- [x] php
- [x] phantomjs
- [x] pgbouncer
- [x] pgadmin3
- [x] pev
- [x] perl-Net-SSLeay
- [x] perl-Net-SSH2
- [x] perl-DBD-mysql
- [x] perl-Crypt-OpenSSL-Random
- [x] perl-Crypt-OpenSSL-RSA
- [x] perl-Crypt-OpenSSL-Bignum
- [x] pen
- [x] partclone
- [x] pam_ssh
- [x] opusfile
- [x] opmsg
- [x] opkg
- [x] openvswitch
- [x] openvpn
- [x] opensmtpd
- [x] opensc
- [x] openntpd
- [x] opendkim
- [x] open-vm-tools
- [x] open-isns
- [x] nzbget
- [x] ntp
- [x] nsd
- [x] nrpe
- [x] nmh
- [x] nmap
- [x] nix
- [x] ngircd
- [x] nginx
- [x] network-ups-tools
- [x] netsurf
- [x] netpgp
- [x] neomutt
- [x] namecoin
- [x] mutt
- [x] mupdf
- [x] mumble
- [x] muchsync
- [x] mtree
- [x] mtd-utils
- [x] mosquitto
- [x] mosh
- [x] monit
- [x] mongoose
- [x] monero-gui
- [x] megatools
- [x] mdcat
- [x] mbuffer
- [x] mbox
- [x] mairix
- [x] mailx
- [x] lynx
- [x] luasec
- [x] lua52-luasec
- [x] loudmouth
- [x] litecoin
- [x] linux5.1
- [x] linux5.0 (removed)
- [x] linux4.19
- [x] linux4.14
- [x] links-x11
- [x] links
- [x] lighttpd
- [x] libucl
- [x] libu2f-server
- [x] libu2f-host
- [x] libtorrent-rasterbar
- [x] libtorrent
- [x] libstrophe
- [x] librdkafka
- [x] libostree
- [x] libmowgli
- [x] libircclient
- [x] libimobiledevice
- [x] libgit2-0.27
- [x] libgdal
- [x] libgda
- [x] libfetch
- [x] lftp
- [x] ldapvi
- [x] lastpass-cli
- [x] kvirc
- [x] kore
- [x] kodi
- [x] kicad
- [x] keepalived
- [x] kea
- [x] john
- [x] isync
- [x] irssi
- [x] ipmiutil
- [x] ipmitool
- [x] inspircd
- [x] inadyn
- [x] imapfilter
- [x] igt-gpu-tools
- [x] icinga2
- [x] icecast
- [x] i2pd
- [x] httrack
- [x] hplip
- [x] hostapd
- [x] hitch
- [x] hfsprogs
- [x] hexchat
- [x] haproxy
- [x] h2o
- [x] gwenhywfar
- [x] grub-customizer
- [x] gogglesmm
- [x] gnome-podcasts
- [x] glusterfs
- [x] gkrellm
- [x] git-series
- [x] git-crypt
- [x] gftp
- [x] getdns
- [x] gcsf
- [x] gatling
- [x] gambit
- [x] freshplayerplugin
- [ ] fractal
- [x] fossil
- [x] ffsend
- [x] fetchmail
- [x] fdm
- [x] falkon
- [x] facter
- [x] ettercap
- [x] encfs
- [x] elog
- [x] ejabberd
- [x] eiskaltdcpp-qt
- [x] eid-mw
- [x] efl
- [x] efitools
- [x] ecryptfs-utils
- [x] dovecot
- [x] dmg2img
- [x] dma
- [x] dillo
- [x] cyrus-sasl
- [x] cryptsetup
- [x] coturn
- [x] collectd
- [x] coWPAtty
- [x] cmusfm
- [x] cloudfuse
- [x] claws-mail
- [x] clamav
- [x] chatterino2
- [x] cargo-outdated
- [x] calibre
- [x] burp2-server
- [x] burp-server
- [x] bro
- [x] botan
- [x] borg
- [x] boinc
- [x] bitlbee
- [x] bitcoin
- [x] bitchx
- [x] barrier
- [x] baresip
- [x] badvpn
- [x] bacula-common
- [x] axel
- [x] attic
- [x] aria2
- [x] argyllcms
- [x] apk-tools
- [x] amp
- [x] alpine
- [x] aircrack-ng
- [x] acme-client
- [x] VirtualGL
- [x] MEGAsdk
- [x] LGOGDownloader
- [x] FreeRADIUS

**Comment by jnbr** [comment]
mostly done, remaining ones:

- [ ] fractal (incompatible with gstreamer-1.16
- [ ] pijul (currently broken)
- [ ] taizen (needs older rust-openssl)
- [ ] zou (needs oler rust-openssl)

**Comment by leahneukirchen** [comment]
Long done.

**Comment by jnbr** [comment]
> Long done.
except fractal
