### ISSUE TITLE
GConf removal

### ISSUE THREAD

**Issue by CameronNemo** [void-linux/void-packages#17254]
Tracking issue for `GConf` removal.

- [x] gconfmm: can be removed at any time, nothing depends on it https://github.com/void-linux/void-packages/pull/38864
- [x] gconf-editor: can be removed with GConf
- [x] vscode: dependency seems to no longer be valid https://github.com/microsoft/vscode/pull/65744
- [x] python-gconf: for hamster-applet, gconf removal is WIP https://github.com/projecthamster/hamster/pull/470
- [x] ogmrip: ~~**no clear migration path**~~
- [x] spotify: GConf dependency has since been removed
- [ ] qt6-location, qt6-position: unclear why these depend on GConf-devel; they do not link to GConf
- [ ] upwork: distfiles seem out of date, perhaps best to also remove this package?

**Comment by xtraeme** [comment]
I'm all for it. About ogmrip... Probably nobody cares for this sw anymore...

**Comment by xtraeme** [comment]
While we are at it. Please remove its stuff from xbps-triggers

**Comment by ndowens** [comment]
ogmrip builds without gconf-devel fine

**Comment by Duncaen** [comment]
I think we should get rid of GConf where we can, but keep the package itself in the repository for some time.
Thirdparty electron binaries will probably depend on it for some time and getting rid of it will add extra steps for people who want to use electron binaries resulting in more package requests for electron stuff.

**Comment by paper42** [comment]
@Duncaen it's been almost 3 years, do you think we can remove GConf now?

**Comment by Duncaen** [comment]
Seems fine.
