### ISSUE TITLE
libgnome-keyring is deprecated

### ISSUE THREAD

**Issue by yopito** [void-linux/void-packages#26333]
superseeded by GNOME libsecret.  
see: https://gitlab.gnome.org/GNOME/libgnome-keyring/blob/master/README

* [x] chromium
* [x] cinnamon
* [ ] electron19
* [x] libcryptui
* [x] libgda
* [x] libpurple-steam
* [x] mate-power-manager
* [x] network-manager-applet
* [x] remmina
* [x] retroshare
* [x] seahorse-nautilus
* [x] subversion-kwallet-auth
* [x] subversion
* [x] telepathy-mission-control

EDIT: formating

**Comment by CameronNemo** [comment]
https://github.com/void-linux/void-packages/pull/4886

**Comment by CameronNemo** [comment]
Also for libcryptui and seahorse-nautilus: https://gitlab.gnome.org/GNOME/libcryptui/-/issues/1

**Comment by CameronNemo** [comment]
Also a lot of these are probably invalid/unneeded build dependencies. Like for subversion. It does not link to libgnome-keyring. I bet you could build without it and have no change in functionality. I'd bet on the same for retroshare, libgda, and others.

**Comment by sgn** [comment]
On 2020-11-12 14:52:22-0800, yopito <notifications@github.com> wrote:
> superseeded by GNOME libsecret.  
> see: https://gitlab.gnome.org/GNOME/libgnome-keyring/blob/master/README
> 
> * [] mate-power-manager

mate-power-manager needs to be linked with libgnome-keyring

**Comment by paper42** [comment]
* nothing links against libgnome-keyring anymore
* mate-power-manager doesn't use libgnome-keyring in 1.26.0 which we have packaged, so the build dep should be removed
* cinnamon doesn't use gnome-keyring since 3.6, so the build dep can also be removed: https://github.com/linuxmint/cinnamon/commit/f912db7f8e8ad3ab73219af18693d07f4c0f6dd1
* libgda 5.1.1:
> - Use Libsecret instead of Libgnome-keyring if available

* libpurple-steam doesn't link against libgnome-keyring, do we have the part disabled and the build dep is unnecessary? We have 1.6.1 packaged, 1.7+ can use libsecret:
> Switch to use libsecret instead of gnome-keyring for Telepathy-Haze users

I didn't check other packages yet.
