### ISSUE TITLE
[Tracking] Packages that depend on wxWidgets webview functionality

### ISSUE THREAD

**Issue by Hoshpak** [void-linux/void-packages#2664]
This is related to #2488 . To be able to remove the webview functionality from wxWidgets (the currently used gtk2 version), all packages that depend on the webview functionality have to be modified in one of the following ways:

* Switch to `wxWidgets-gtk3` so they can use its webview functionality provided by `webkit2gtk`
* Recompile without the functionality that requires the webview component

The affected packages are:

- [x] DarkRadiant (#2667)
- [x] SLADE (cannot be compiled with gtk3 in the current release, #2666)
- [x] boinc (#2668)
- [x] codeblocks (#2673)
- [x] codelite (doesn't detect the gtk3 version, can work without webview, #2681)
- [x] wxPython (will be superseded by wxPython4 for gtk3, can work without webview, #2681)
