### ISSUE TITLE
[Tracking] Packages depending on wxWidgets

### ISSUE THREAD

**Issue by Hoshpak** [void-linux/void-packages#2665]
The following packages currently depend on wxWidgets (gtk2 version). They should be checked if they can be built against `wxWidgets-gtk3` instead:

- [x] 0ad (#2684)
- [x] Aegisub (#2676)
- [x] DarkRadiant (#2667)
- [x] SLADE (does not build with gtk3 yet)
- [x] VeraCrypt (#2659)
- [x] WoeUSB (#2674)
- [x] audacity (#2677)
- [x] boinc (#2668)
- [x] codeblocks (#2673)
- [x] codelite (#2711 )
- [x] diff-pdf (#2707)
- [x] dolphin-emu (does not built with gtk3 yet)
- [x] filezilla (#2670)
- [x] gnuplot-wx (#2708)
- [x] golly (waiting for next release)
- [x] hugin (#2687)
- [x] kicad (has bugs with gtk3, should stay on wxWidgets)
- [x] mediainfo (#2635)
- [x] openbabel (#2660)
- [x] passwordsafe (#2682)
- [x] pgadmin3 (#2709)
- [x] poedit (#2661)
- [x] treesheets (#2662)
- [x] vba-m (#2686)
- [x] winusb (#2675)
- [x] wxMaxima (#2678)
- [x] wxPython (will be superseded by wxPython4)
- [x] xchm (#2663)
- [x] pcsx2 (experimental support, not recommended by upstream yet)

**Comment by maxice8** [comment]
Working on Filezilla

**Comment by newbluemoon** [comment]
As of version 3.2 golly doesn’t support gtk3, but it has been added upstream by now. So the switch can be made when version 3.3 is released.

https://sourceforge.net/p/golly/bugs/44/
