### ISSUE TITLE
Replace enchant with enchant2

### ISSUE THREAD

**Issue by gspe** [void-linux/void-packages#27710]
Would be nice to completely replace the old enchant with new enchant2.

Currently following packages are built with the old enchant as dependency:
- [x] abiword --> old tls download doesn't works
- [x] libabiword --> old tls download doesn't works
- [x] balsa --> compile fine but need test  #27711
- [x] empathy --> empathy is no longer developed, maybe can be removed from the repository
- [x] hexchat --> works fine #27702
- [x] kadu --> kadu is no longer developed, maybe can be removed from the repository (see #12548)
- [x] libgtkhtml --> gtkhtml is no longer developed and replaced by webkit2gtk, maybe can be removed from the repository (has already been removed from repo)
- [x] lyx --> compile fine but need test  #27713
- [x] mcabber
- [x] php-enchant
- [x] python-enchant --> maybe can be removed from the repository #28117
- [x] python3-enchant --> compile fine but need test #28107
- [x] webkit2gtk --> compile fine but need test #28099
- [x] weechat-aspell
- [ ] fcitx

**Comment by ericonr** [comment]
Do you have a PR for webkit2gtk?

**Comment by gspe** [comment]
Yeah I have a PR for webkit2gtk, but since it's big package that take long time to build I haven't pushed it yet.
I'll push it tomorrow.

**Comment by gspe** [comment]
@ericonr I've pushed a PR for Webkit2gtk #28099

**Comment by ericonr** [comment]
I saw it, have yet to test though.

Can you make a PR to drop python-enchant as well?

**Comment by gspe** [comment]
I'm working on it

**Comment by heliocat** [comment]
Been looking at the remaining packages here. mcabber upstream depends on enchant v1. Short of getting them to fix it or patching the build to use enchant2 it's probably a lost cause. However, it does look like mcabber can use aspell as a backend directly so that's an option. Since mcabber isn't orphaned I'll let @sternenseemann take a look.

**Comment by heliocat** [comment]
Same deal with weechat-aspell it looks like. Changing the makedepends to include aspell-devel instead of enchant-devel and dropping -DENABLE_ENCHANT=ON links spell.so against libaspell directly. @leahneukirchen I can update this unless you want to get it. v3.0.1 also was released and has a few bug fixes mostly around spelling, so it might make sense to roll the two together.

**Comment by gspe** [comment]
@heliocat Yeah this is what Arch linux did, they build `mcabber` and `weechat` without enchant using aspell.

Regarding `php` they support enchant-2 form the 8 release so I don't think is worth to patch the 7.x version to support it.

**Comment by sternenseemann** [comment]
See #28583

**Comment by leahneukirchen** [comment]
weechat fixed in a5cadcf49d1bb

**Comment by ericonr** [comment]
abiword fixed in 9160a19b834401f1f9fa71da4df1f15cfec0bc26

**Comment by mtboehlke** [comment]
php fixed in afde904f6d2047de7ffc5095452fa46a9b593c95

**Comment by leahneukirchen** [comment]
After removing the dead packages `kadu` and ` libgtkhtml` from repo we can drop `enchant` now.
