### ISSUE TITLE
Tracking issue: packages marked broken in openssl rebuild

### ISSUE THREAD

**Issue by fosslinux** [void-linux/void-packages#29265]
Some packages may need to be marked broken during the OpenSSL rebuild in order to keep the build running smoothly.

- [x] kicad (cross) @ericonr
- [x] monero-gui (cross)  #29266
- [x] seafile-libclient 1f26ec6bbf60af0fdd10cf124bde4738325743b0 <-- we'll see if it breaks again

**Comment by ericonr** [comment]
I believe we are done here, thanks for tracking stuff :D
