### ISSUE TITLE
[TRACKING] Packages unable to cross-build due to rust's autocfg

### ISSUE THREAD

**Issue by cinerea0** [void-linux/void-packages#34889]
Some rust packages are currently failing to cross-build because they depend on indexmap. A default hash builder only exits for std builds; this is checked in indexmap's build.rs file, and that test is currently failing for us. We don't want to fix it with the environment variable because the autocfg tests should be working.

Packages that have been merged:
- [ ] alacritty (https://github.com/void-linux/void-packages/commit/bb096521bab955c4bc72fd312ae25a53ee91bc68)

Packages with open PRs:
- [ ] sequoia-sq (https://github.com/void-linux/void-packages/pull/32480)

Fixed packages:
- [x] bat (https://github.com/void-linux/void-packages/pull/34966)
- [x] delta (https://github.com/void-linux/void-packages/commit/48fa12c7177122900f275446a043a8b839e77dcf)
- [x] git-cliff (https://github.com/void-linux/void-packages/pull/35489)
- [x] gitui (https://github.com/void-linux/void-packages/pull/35490)
- [x] mdcat (https://github.com/void-linux/void-packages/commit/66eaeca1072cbc8a98c00f552648a4101108657c)
- [x] rust-analyzer (https://github.com/void-linux/void-packages/pull/34856)
- [x] starship (https://github.com/void-linux/void-packages/pull/34850) (Fixed on its own)
- [x] texlab (https://github.com/void-linux/void-packages/commit/9f22215912441436bd9314a438838b6a89972f6d)
- [x] tree-sitter (https://github.com/void-linux/void-packages/commit/a93c5322d34603901cf0ab5be9014ea39b2e2cf4)

**Comment by abenson** [comment]
`indexmap` is the first thing most things fail on, but there are more all centered around `autocfg`.

**Comment by ericonr** [comment]
:upside_down_face:

**Comment by cinerea0** [comment]
I'm going to start a separate comment to list packages that have the error but haven't been merged or don't have open PRs since they're not as high priority. The list:
* fselect

**Comment by ericonr** [comment]
I came across this while investigating, might have something to do with it https://github.com/LibreELEC/LibreELEC.tv/pull/5446

https://github.com/rust-lang/cargo/pull/9322 got merged right after the release we were using. Should be unstable and not affect anything, but who knows for sure.

https://github.com/cuviper/autocfg/issues/15 might be the relevant one? but unsure

**Comment by paper42** [comment]
gitui is another one: #35490

**Comment by tranzystorek-io** [comment]
From https://github.com/google/cargo-raze/issues/114#issuecomment-547080315:

> (Nitty gritty aside: It seem the way this works is the autocfg library tries to run rustc over a file containing the single "extern $some_crate", and identifies whether or not that compiles)

Maybe building a file like:

```rust
extern crate std;
```

on the failing targets could point to the cause of this problem?

**Comment by tranzystorek-io** [comment]
Did a bit of analysis on a test repo where I added some debug printouts to `autocfg`, and I seem to have found the problem.

When autocfg probes for the std crate, it runs a custom `rustc` command with arguments that try to mimic the settings of the crate that is being built. In our case, that should include a custom `--sysroot=<XBPS_CROSS_BASE>/usr` argument, pointing to the rust-std install for the cross target.

Unfortunately, we pass this as the RUSTFLAGS environment variable, and the build.rs script run, being a subprocess in a new shell context, doesn't see any RUSTFLAGS in its environment.

In the end the `rustc` probe is run with almost all the needed arguments, except for the `--sysroot`.

**Comment by tranzystorek-io** [comment]
It's probably unreasonable to skip the affected packages' versions, but I'm not sure if we can somehow make patches that force just the autocfg bump, similar to running `cargo update --package autocfg`

**Comment by jcgruenhage** [comment]
If it's just updating autocfg to 1.1.0 in the deps, `cargo update --package autocfg --precise 1.1.0` should do it, no need to actually write patches for that.

https://github.com/void-linux/void-packages/pull/35490/files#diff-6e15b2c2a57581f8262281a6d3343049c12e4de3c59ec1455fc8bb8027846d15R16-R18 is running that line in `post_patch`, which locally made cross compiling to aarch64 work for gitui locally. Let's see how that does for the other packages and other architectures in CI.

**Comment by jcgruenhage** [comment]
So yeah, seems like gitui and cargo-deny now pass their CI!

**Comment by tranzystorek-io** [comment]
zellij also seems to build locally for aarch64 😄

**Comment by tranzystorek-io** [comment]
Another problem with this issue in #35768. Probably cannot update autocfg to 1.1.0 there easily since the num-bigint-dig dependency selects autocfg 0.1.5

**Comment by tranzystorek-io** [comment]
As per https://github.com/cuviper/autocfg/issues/40, autocfg 0.1 versions need to be updated to 0.1.8

**Comment by cinerea0** [comment]
Adding the following lines will likely fix any unfixed packages (credit to @tranzystorek-io) :

```sh
post_patch() {
	# fixes an indexmap error when cross compiling
	cargo update --package autocfg --precise 1.1.0
}
```

**Comment by jcgruenhage** [comment]
Probably can be closed. One thing that might still be worth mentioning is that xlint requires specific versions by now, so the solution suggested here has to be adapted slightly:

```
cargo update --package autocfg:1.0.1 --precise 1.1.0
cargo update --package autocfg:0.1.7 --precise 0.1.8
```

**Comment by cinerea0** [comment]
Yeah, this should be fine to close now that there's a general solution.
