### ISSUE TITLE
[tracking] Builds failing due to wrong checksum

### ISSUE THREAD

**Issue by paper42** [void-linux/void-packages#39072]
- [x] go-ipfs
- [x] lua54-luaexpat
- [x] luakit
- [x] ocaml-stdcompat
- [x] oragono (#37645, #34581)
- [x] pari-nflistdata
- [x] pasmo
- [x] phorward
- [x] python-tkinter
- [x] python3-pyFFTW
- [x] python3-watchman
- [x] singular
- [x] source-sans-pro
- [x] steam-fonts
- [x] stfl
- [x] tcllib
- [x] tcpflow
- [x] tidy5
- [x] wev
- [x] xwinwrap
- [x] adwaita-qt
- [x] ffuf
- [x] glmark2
- [x] openpgp-card-tools
- [x] qprompt
- [x] python3-pyFFTW (again?)

**Comment by dkwo** [comment]
Both pari-nflistdata and singular are now fine.

**Comment by pascal-huber** [comment]
As for `stfl`: The distfiles are not available anymore on clifford.at/stfl. The svn repo also is unavailable. The website seems a bit suspicious with all the casino ads. This seems to be a copy of the project: https://github.com/dennisschagt/stfl (without tags/releases but probably the right version). Not sure what to do here. Remove the package?

**Comment by ajtcode71** [comment]
i think these apps can be marked off the list.

 adwaita-qt - passed checksum and compiles.
ffuf: tested. Needs to be checked off too, as per above posted. 
qprompt: passed checksum and compiling.
openpgp-card-tools: passed checksum and compiling.

**Comment by vincele** [comment]
Tried just now:
* python3-pyFFTW => `python3-pyFFTW-0.15.0_1`.
* oragono (it was renamed to ergo in [this PR](https://github.com/void-linux/void-packages/pull/45805)) => `ergo-2.16.0_1`.

They both built fine, native (x86_64-musl) & cross (aarch64) without checksum problems.
