### ISSUE TITLE
[tracking] Drop mozjs78

### ISSUE THREAD

**Issue by JamiKettunen** [void-linux/void-packages#39226]
As per https://endoflife.date/firefox 78 ESR has been EoL for nearly a year soon. According to a quick `grep -r` only the following consumers remain:
- [ ] [`0ad`](https://github.com/void-linux/void-packages/pull/46525)
- [x] [`cjs`](https://github.com/linuxmint/cjs/compare/5.6.1...1ef6934)
- [x] [`polkit`](https://github.com/void-linux/void-packages/pull/39203)

This would also contribute to #38229 ([`mozjs78`](https://github.com/void-linux/void-packages/blob/master/srcpkgs/mozjs78/template#L11) has `python-devel` in `makedepends`).

We should also keep in mind what happened with `mozjs60`: [5121c0f](https://github.com/void-linux/void-packages/commit/5121c0f) (`mozjs60: re-add as meta to allow people to upgrade their systems`) so the same thing doesn't happen again with the removal of `mozjs78`.

**Comment by paper42** [comment]
polkit: https://github.com/void-linux/void-packages/pull/39203

**Comment by CameronNemo** [comment]
From what I can tell 0ad is only compatible with mozjs78.

**Comment by CameronNemo** [comment]
Mint seemingly has plans to upgrade off of mozjs78: https://github.com/linuxmint/cjs/issues/102

**Comment by CameronNemo** [comment]
To build 0ad, Arch just patches the vendored mozjs to build with python3 AFAICT. https://github.com/archlinux/svntogit-community/blob/packages/0ad/trunk/python-3.10.patch

**Comment by classabbyamp** [comment]
I think that 0ad patch is reasonable, until they update their mozjs

**Comment by mhmdanas** [comment]
cjs is now upgraded off of mozjs78.
