### ISSUE TITLE
[TRACKING] gcc 12 build failures

### ISSUE THREAD

**Issue by Duncaen** [void-linux/void-packages#39809]
https://vasilek.cz/logs/gcc12-musl/bad/

- [x] Carla
- [x] The-Powder-Toy
- [x] XQilla
- [x] advancecomp
- [x] afterstep
- [x] amdvlk
- [x] apl
- [x] asignify
- [x] attract
- [x] barrier
- [x] bctoolbox
- [x] beignet
- [x] bish
- [x] blackboxwm
- [x] blobby2
- [x] bonnie++
- [x] ccache
- [x] cglm
- [x] chromium
- [x] clucene
- [x] codeblocks
- [x] codelite
- [x] commoncpp2
- [x] coreboot-utils
- [x] cross-powerpc64le-linux-gnu
- [x] cross-powerpcle-linux-gnu (marked broken)
- [x] cross-x86_64-w64-mingw32
- [x] darkice
- [x] darkplaces
- [x] edb-debugger
- [x] electron19 (#40890)
- [x] endless-sky-gl21
- [x] facter
- [x] ffmpeg
- [x] flatbuffers
- [x] fluxbox
- [x] freeimage
- [x] fsearch
- [x] ghdl #40614 
- [x] glmark2
- [x] glog
- [x] gloox
- [x] glslViewer
- [x] goldendict
- [x] grive2
- [x] grub-customizer
- [x] gstreamermm
- [x] hashdeep
- [x] htmlcxx
- [x] igt-gpu-tools
- [x] incron
- [x] ipv6calc
- [x] jigdo
- [x] john
- [x] juCi++
- [x] kakoune
- [x] kea
- [x] kodi-addon-pvr-hts
- [x] ldc https://github.com/void-linux/void-packages/pull/40931
- [x] leatherman
- [x] libbitcoin-system
- [x] libebml
- [x] libgdal
- [x] liblastfm-qt5
- [x] libomxil-bellagio
- [x] libpgf
- [x] libreoffice
- [x] linux4.14
- [x] linux4.9
- [x] lyx
- [x] melonDS
- [x] mercury
- [x] mimic
- [x] monero-gui
- [x] mpdscribble
- [x] msp430-toolchain
- [x] netpgp
- [x] network-ups-tools
- [x] nmap
- [x] ogmtools
- [x] openbabel
- [x] openjdk10-bootstrap
- [x] openjdk9-bootstrap
- [x] openmsx
- [x] openmw
- [x] opensc
- [x] owncloudclient
- [x] papi
- [x] passwordsafe
- [x] psensor
- [x] qemu-user-static
- [x] qemu
- [x] qt5-doc
- [x] qv4l2
- [x] rdfind
- [x] retroshare
- [x] rlottie
- [x] rmilter
- [x] rocksdb
- [x] rstudio
- [x] singular
- [x] slim
- [x] snapper
- [x] source-highlight
- [x] subtitleeditor
- [x] supertux2
- [x] tab
- [x] textadept
- [x] textosaurus
- [x] ucommon
- [x] uhd
- [x] unittest-cpp
- [x] upx
- [x] vtk
- [x] xstow
- [x] xwmfs
- [x] yosys
- [x] zeromq
- [x] zynaddsubfx

**Comment by oreo639** [comment]
> igt-gpu-tools

That should be fixed here https://github.com/void-linux/void-packages/pull/39780.

**Comment by Anachron** [comment]
Can we tag maintainers or at least add their email addresses? 
If I saw that correctly none of them is maintained by me.

**Comment by Duncaen** [comment]
No I don't want to have to wait 5 months because 100 different people fix minor issues.

**Comment by oreo639** [comment]
> cross-powerpc64le-linux-gnu

I can't reproduce this build failure?

> cross-powerpcle-linux-gnu

This is caused by glibc using big-endian specific instructions (that would normally trigger an exception in little-endian mode) that got blacklisted when assembling little-endian code in binutils 2.36.

Would it be best to just mark the package as broken for now?

> cross-x86_64-w64-mingw32

That should be able to be fixed by updating it to gcc 12.2+:
https://github.com/gcc-mirror/gcc/commit/de6f402a54f7e6a3f8a79d723a25724e6274cc3e
https://github.com/gcc-mirror/gcc/commit/ad5d760b815b3d491bdb5d97f6e053d60d6991b9

**Comment by dkwo** [comment]
`singular` should be fixed by #39866

**Comment by oreo639** [comment]
The qemu build failure is this: https://github.com/void-linux/void-packages/blob/master/srcpkgs/qemu/patches/musl-fix-sigevent-and-sigval_t.patch

The patch will need to be removed in the gcc12 PR.

**Comment by oreo639** [comment]
I was able to fix the build failure in openjdk10-bootstrap with gcc 12, however after that I get a build failure with glibc 2.36:
https://gist.github.com/oreo639/470e234e45134c56383bf722dd2d1ccb

**Comment by oreo639** [comment]
The ffmpeg build failure isn't related to gcc 12 and has already been resolved: https://github.com/void-linux/void-packages/issues/39648

Here is the libreoffice build failure on musl:
```
configure:23848: checking for CLucene/analysis/cjk/CJKAnalyzer.h
configure:23848: /usr/bin/ccache g++ -c -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe   -DGLM_ENABLE_EXPERIMENTAL -DU_USING_ICU_NAMESPACE=1 -DGLM_ENABLE_EXPERIMENTAL -DU_USING_ICU_NAMESPACE=1  -fdebug-prefix-map=/builddir/libreoffice-7.3.3.2=.       conftest.cpp >&5
In file included from /usr/include/CLucene/debug/lucenebase.h:10,
                 from /usr/include/CLucene/SharedHeader.h:201,
                 from /usr/include/CLucene/StdHeader.h:20,
                 from /usr/include/CLucene.h:11,
                 from conftest.cpp:90:
/usr/include/CLucene/LuceneThreads.h:72:24: error: 'pthread_t' does not name a type
   72 |                 static _LUCENE_THREADID_TYPE _GetCurrentThreadId();
      |                        ^~~~~~~~~~~~~~~~~~~~~
/usr/include/CLucene/LuceneThreads.h:73:32: error: 'pthread_t' does not name a type
   73 |                         static _LUCENE_THREADID_TYPE CreateThread(luceneThreadStartRoutine* func, void* arg);
      |                                ^~~~~~~~~~~~~~~~~~~~~
/usr/include/CLucene/LuceneThreads.h:74:48: error: 'pthread_t' has not been declared
   74 |                         static void JoinThread(_LUCENE_THREADID_TYPE id);
      |                                                ^~~~~~~~~~~~~~~~~~~~~
```

**Comment by dkwo** [comment]
`singular` has now been updated, so it should be fine.

**Comment by oreo639** [comment]
The ldc build failure seems to be a segfault in ldc2.
The crash location I got was:
https://github.com/ldc-developers/ldc/blob/master/gen/target.cpp#L180
Here is a snippet of the disas:
```
...
   0x000000000095e6ca <+1402>:	xor    %esi,%esi
   0x000000000095e6cc <+1404>:	mov    $0xaaf859,%edi
   0x000000000095e6d1 <+1409>:	fstpt  0x180(%rbx)
   0x000000000095e6d7 <+1415>:	call   0x913210 <_ZN7CTFloat5parseEPKcPb>
   0x000000000095e6dc <+1420>:	xor    %esi,%esi
   0x000000000095e6de <+1422>:	mov    $0xaaf864,%edi
   0x000000000095e6e3 <+1427>:	fstpt  0x190(%rbx)
   0x000000000095e6e9 <+1433>:	call   0x913210 <_ZN7CTFloat5parseEPKcPb>
   0x000000000095e6ee <+1438>:	movdqa 0x15138a(%rip),%xmm0        # 0xaafa80
   0x000000000095e6f6 <+1446>:	fstpt  0x1c0(%rbx)
=> 0x000000000095e6fc <+1452>:	movaps %xmm0,0x1d0(%rbx)
```

**Comment by oreo639** [comment]
ldc should be fixed by https://github.com/void-linux/void-packages/pull/41158
