### ISSUE TITLE
[Tracking] Packages with multiple distfiles without create_wrksrc

### ISSUE THREAD

**Issue by paper42** [void-linux/void-packages#40071]
Packages that have multiple distfiles should use create_wrksrc to make sure all sources get cleaned up when the build is done and everything is contained in one directory. Manual.md already instructs people to use create_wrksrc every time there are multiple distfiles, but in practice there is a lot of templates that don't follow this.

- [ ] 7kaa
- [ ] EmptyEpsilon
- [ ] EmulationStation
- [ ] Fritzing
- [ ] LanguageTool
- [ ] OpenRCT2
- [ ] Waybar
- [ ] Z80Explorer
- [ ] acmetool
- [ ] antlr3-bin
- [ ] apache-fop
- [ ] apache-maven
- [ ] app-builder
- [ ] arcan
- [ ] avahi
- [ ] avahi-discover
- [ ] babashka
- [ ] barrier
- [ ] bitcoin
- [ ] browsh
- [ ] bumblebee-status
- [ ] cargo
- [ ] cavestory
- [ ] cgit
- [ ] choosenim
- [ ] composer
- [ ] composer8.0
- [ ] composer8.1
- [ ] cracklib
- [ ] crda
- [ ] daemontools
- [ ] deadbeef
- [ ] debootstrap
- [ ] dolphin-emu
- [ ] ekushey-fonts-ttf
- [ ] exa
- [ ] fah
- [ ] fairy-stockfish
- [ ] fcitx
- [ ] fcitx-libpinyin
- [ ] fcitx5
- [ ] fcitx5-chinese-addons
- [ ] fcitx5-zhuyin
- [ ] gendesk
- [ ] gmic
- [ ] grafana
- [ ] grafx2
- [ ] gucharmap
- [ ] gzdoom
- [ ] ipe
- [ ] jmol
- [ ] juCi++
- [ ] kristall
- [ ] lc0
- [ ] leiningen
- [ ] leocad
- [ ] libime
- [ ] libime-jyutping
- [ ] libluv
- [ ] libpinyin
- [ ] lightzone
- [ ] maturin
- [ ] minetest
- [ ] mkinitcpio-encryptssh
- [ ] monero
- [ ] monero-gui
- [ ] mons
- [ ] mpc-qt
- [ ] msttcorefonts
- [ ] musescore
- [ ] notmuch
- [ ] nsjail
- [ ] ocs-url
- [ ] offo-hyphenation
- [ ] openjdk15-bootstrap
- [ ] openjdk16-bootstrap
- [ ] opensonic
- [ ] par
- [ ] pasmo
- [ ] perl
- [ ] pijul
- [x] pipewire 5d02a92eede1ff48ac50ed634c4871d281c2ec18
- [ ] plex-media-player
- [ ] poppler
- [ ] prometheus-cpp
- [ ] pymol
- [ ] python3-colored-traceback
- [ ] python3-discogs_client
- [ ] python3-pytest-xvfb
- [ ] python3-webencodings
- [ ] qflipper
- [ ] qt5-webengine
- [ ] radamsa
- [ ] renderdoc
- [ ] rstudio
- [ ] sage-data-conway_polynomials
- [ ] sage-data-elliptic_curves
- [ ] sbsigntool
- [ ] sc
- [ ] sc3-plugins
- [ ] scrcpy
- [ ] solvespace
- [ ] stack
- [ ] stockfish
- [ ] stremio-shell
- [ ] sunpinyin
- [ ] tcpflow
- [ ] textadept
- [ ] tg_owt
- [ ] tigervnc
- [ ] tty-clock
- [ ] tvbrowser
- [ ] upwork
- [ ] volk
- [ ] wabt
- [ ] wally-udev-rules
- [ ] wasmtime
- [x] wayfire 2d4987a20bb498bdeab34e1db8c17447a138ac11
- [ ] words-web2
- [ ] yaboot

**Comment by JamiKettunen** [comment]
I'll add my comment here just in case it gets lost in `#xbps`: in the future couldn't we just e.g. make `xbps-src` error (in strict mode?) in case there's a space / newline character in the `distfiles` without `create_wrksrc` set? could possibly work as an addition to `xlint` as well

**Comment by classabbyamp** [comment]
imo it would be better to automatically set create_wrksrc if there's multiple distfiles

**Comment by tranzystorek-io** [comment]
`iaito` seems to only have one distfile, a typo of sorts?

**Comment by paper42** [comment]
> `iaito` seems to only have one distfile, a typo of sorts?

It was a wrong grep that matched many false positives, removed now, thanks!

**Comment by tranzystorek-io** [comment]
`fs-utils` skips extraction of the license distfile, is `create_wrksrc` necessary in this case?

**Comment by sgn** [comment]
> `fs-utils` skips extraction of the license distfile, is `create_wrksrc` necessary in this case?

IMO, yes, it will help move to auto create wrksrc later easier. So, we won't have case like:
- building cmake-gui to ensure build is good after updating Qt, run into failure
- try to build cmake to see if it's still good. Now, `cmake` will use `cmake-gui`'s `wrksrc`

Also, case to consider set `-fdebug-prefix-map=$wrksrc/$build_wrksrc`, (OK, this has been done by me).
`-ffile-prefix-map` and `-fmacro-prefix-map`

**Comment by sgn** [comment]
That said, if the number of distfiles that not in skip_extraction list is 1, we should avoid create_wrksrc, but that's another story.

**Comment by sgn** [comment]
Now #40122 has been merged, I think we should close this now.
