### ISSUE TITLE
[TRACKING] Updates blocked on Rust 1.65.0

### ISSUE THREAD

**Issue by jcgruenhage** [void-linux/void-packages#40805]
~~We can't update to Rust 1.65.0 yet, because that requires LLVM >= 13 (see #40821), which in turn is waiting for a GCC update (see #34902, #39809, #39960)~~.

### Updates blocked on Rust 1.65.0
- [x] #43179
- [x] https://github.com/void-linux/void-packages/pull/43244
- [x] #43219
- [x] #43188
- [x] #43217
- [x] #43212
- [ ] #43223
- [x] #43175
- [x] #43181
- [x] #43200 
- [x] #43173
- [x] #43218
- [x] #43177
- [x] #43213
- [x] https://github.com/void-linux/void-packages/pull/43240

### New packages blocked on Rust 1.65.0
- [x] prose (https://github.com/void-linux/void-packages/commit/27a54bff68bf410430305984b44d62f14ca1517b)
- [x] #40787 
- [x] #43203
- [x] #43185
- [x] #40600

**Comment by icp1994** [comment]
rust-analyzer and qsv are two that I know of

**Comment by jcgruenhage** [comment]
Isn't rust-analyzer shipped by rustup though? Not sure whether it makes sense to ship that separately. We removed rustfmt back when it started being shipped by rustup, although that had additional reasons related to requiring nightly iirc.

**Comment by icp1994** [comment]
From the 1.64 [release blog](https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html#rust-analyzer-is-now-available-via-rustup)

> At this time, to run the rustup-installed version, you need to invoke it this way: `rustup run stable rust-analyzer`
The next release of rustup will provide a built-in proxy so that running the executable `rust-analyzer` will launch the appropriate version.

> Most users should continue to use the releases provided by the rust-analyzer team (available on the [rust-analyzer releases page](https://github.com/rust-lang/rust-analyzer/releases)), which are published more frequently

Not exactly sure what should be done regarding the RA package after the next rustup update but okay maybe it can left from the list for now.

**Comment by jcgruenhage** [comment]
Ah, okay, so we still need rust-analyzer until we get a new rustup release at least.. In that case, I think we should add it to the list here.

**Comment by 0x5c** [comment]
Unless we mark the rust toolchain packages as "for package building only", there will be people using the rust toolchain bits we ship instead of whatever they'd otherwise download through rustup.

The current setup allows all the toolchain to be installed through xbps without rustup involvement, no mix needed. People using packaged rust with rustup-downloaded r-a won't even get the same version unless they specifically ensure they keep the packaged rust and rustup r-a in version sync.

I don't personally use packaged rust outside of when packaging other things, and I'm not sure using packaged rust is good for development purposes, but such is the current state of what we ship.

**Comment by icp1994** [comment]
[nushell](https://www.nushell.sh/blog/2022-11-29-nushell-0.72.html#minimum-rust-version-has-bumped-to-1-65)

**Comment by icp1994** [comment]
[pueue >= 3.0.0](https://github.com/Nukesor/pueue/commit/e576126b187cee2543a2097634917887182a583c)

**Comment by cinerea0** [comment]
bottom >= 0.7.0 [requires let-else statements](https://github.com/ClementTsang/bottom/blob/master/src/app/data_harvester/processes/linux.rs#L262) which were stabilized in 1.65.

**Comment by leahneukirchen** [comment]
I want to package [prose](https://github.com/jgdavey/prose/) but a depenency needs 1.65.

**Comment by cinerea0** [comment]
broot >= 1.19.0 requires 1.65.

**Comment by tranzystorek-io** [comment]
[`zoxide` >= 0.9.0](https://github.com/ajeetdsouza/zoxide/commit/d99e9b7d8671946dafe53662c519045f84d1d334)

**Comment by cinerea0** [comment]
ouch >= 0.4.1 [requires let-else statements](https://github.com/ouch-org/ouch/blob/main/src/extension.rs#L147).

**Comment by tranzystorek-io** [comment]
Preliminary test on llvm15/rust 1.66.1/x86_64-glibc:

- [x] cargo-about `0.5.2`
- [x] qsv `0.84.0`
- [x] rust-analyzer `2023.01.09`
- [ ] nushell `0.74.0` (haven't yet updated system libs patch)
- [ ] pueue `3.0.1` (fails to build due to darwin-libproc: http://ix.io/4lkO)
- [x] bottom `0.7.1`
- [x] broot `1.19.0`
- [x] zoxide `0.9.0`
- [x] cargo-deny `0.13.7`
- [x] ouch `0.4.1`
- [x] prose `0.4.0`

**Comment by classabbyamp** [comment]
helvum >= 0.4.0 (let-else statements) (https://github.com/classabbyamp/void-packages/commit/4d1222b63cf38c248b4536a4278caf6be5d9d5fa)

**Comment by cinerea0** [comment]
Kooha >= 2.2.3 uses let-else statements [all](https://github.com/SeaDve/Kooha/blob/main/src/area_selector/view_port.rs#L213) [over](https://github.com/SeaDve/Kooha/blob/main/src/audio_device.rs#L62) [the](https://github.com/SeaDve/Kooha/blob/main/src/screencast_session/variant_dict.rs#L46) [place](https://github.com/SeaDve/Kooha/blob/main/src/settings.rs#L65).

**Comment by tranzystorek-io** [comment]
atuin >= 13.0.0, let-else statements

**Comment by cinerea0** [comment]
mdcat >= 1.1.0 requires GATs, which were stabilized in rust 1.65.

**Comment by classabbyamp** [comment]
rbw 1.6.0, let else statements

**Comment by tranzystorek-io** [comment]
new package fend >= 1.1.5, let-else statements

**Comment by icp1994** [comment]
procs >= 0.14.0 [msrv 1.67]

**Comment by leahneukirchen** [comment]
I want to package [typst](https://github.com/typst/typst) but a dependency uses let..else.

**Comment by TinfoilSubmarine** [comment]
`vaultwarden-1.28.0` needs `argon2 v0.5.0` which requires rustc >= 1.65:
```
error: package `argon2 v0.5.0` cannot be built because it requires rustc 1.65 or newer, while the currently active rustc version is 1.64.0
```

**Comment by lukas-jo** [comment]
ncspot >= 0.12.0 uses the [backstrace api](https://github.com/hrkfdn/ncspot/pull/988) which was [stabilized in rust 1.65](https://github.com/rust-lang/rust/pull/99573)

**Comment by tranzystorek-io** [comment]
helix >= 23.03, MSRV set to 1.65

**Comment by classabbyamp** [comment]
new rust merged, get em while they're fresh!
