### ISSUE TITLE
[Tracking] libressl-2.8

### ISSUE THREAD

**Issue by jnbr** [void-linux/void-packages#4400]
This is to keep track of the libressl-2.8 bump.

Packages to be bumped:
- [x] acme-client
- [x] aircrack-ng
- [x] alpine
- [x] amp
- [x] apache
- [x] apk-tools
- [x] apr-util
- [x] argyllcms
- [x] aria2
- [x] attic
- [x] axel
- [x] bacula-common
- [x] badvpn
- [x] balsa
- [x] baresip
- [x] barrier
- [x] bind
- [x] bitchx
- [x] bitcoin
- [x] bitlbee
- [x] boinc
- [x] borg
- [x] botan
- [x] bro
- [x] burp2-server
- [x] burp-server
- [x] calibre
- [x] cargo
- [x] clamav
- [x] cloudfuse
- [x] cmusfm
- [x] collectd
- [x] coturn
- [x] coWPAtty
- [x] cryptsetup
- [x] ctpp2
- [x] curl
- [x] cyrus-sasl
- [x] dillo
- [x] dma
- [x] dmg2img
- [x] dovecot
- [x] ecryptfs-utils
- [x] efl
- [x] eid-mw
- [x] eiskaltdcpp-qt
- [x] ejabberd
- [x] elinks
- [x] encfs
- [x] erlang
- [x] ettercap
- [x] facter
- [x] falkon
- [x] fdm
- [x] fetchmail
- [x] fossil
- [x] fractal
- [x] FreeRADIUS
- [x] freerdp
- [x] freshplayerplugin
- [x] gambit
- [x] gatling
- [x] gcsf
- [x] gftp
- [x] git
- [x] git-crypt
- [x] git-series
- [x] gkrellm
- [x] glusterfs
- [x] gnome-podcasts
- [x] godot
- [x] grub-customizer
- [x] gsoap
- [x] gst-plugins-bad1
- [x] gutenberg
- [x] gwenhywfar
- [x] h2o
- [x] haproxy
- [x] hexchat
- [x] hfsprogs
- [x] hitch
- [x] hostapd
- [x] hplip
- [x] httperf
- [x] httrack
- [x] i2pd
- [x] Ice
- [x] icecast
- [x] icinga2
- [x] imapfilter
- [x] inadyn
- [x] inspircd
- [x] ipmitool
- [x] ipmiutil
- [x] iputils
- [x] irssi
- [x] isync
- [x] john
- [x] kea
- [x] keepalived
- [x] kicad
- [x] kvirc
- [x] lastpass-cli
- [x] ldapvi
- [x] ldns
- [x] lftp
- [x] LGOGDownloader
- [x] libarchive
- [x] libesmtp
- [x] libetpan
- [x] libevent
- [x] libfetch
- [x] libgda
- [x] libgdal
- [x] libgit2
- [x] libimobiledevice
- [x] libmowgli
- [x] libostree
- [x] librdkafka
- [x] libssh
- [x] libssh2
- [x] libstrophe
- [x] libtorrent
- [x] libtorrent-rasterbar
- [x] libu2f-host
- [x] libu2f-server
- [x] libucl
- [x] libvncserver
- [x] libwebsockets
- [x] libzip
- [x] lighttpd
- [x] links
- [x] links-x11
- [x] linux4.14
- [x] linux4.17 deleted from repo 4eba8531478b604fbb82705cb4227d05d495cae9
- [x] linux4.18
- [x] linux4.19
- [x] litecoin
- [x] loudmouth
- [x] lua51-luasec
- [x] lua52-luasec
- [x] luasec
- [x] lynx
- [x] mailx
- [x] mairix
- [x] mariadb
- [x] mbox
- [x] mbuffer
- [x] mdcat
- [x] MEGAsdk
- [x] megatools
- [x] mit-krb5
- [x] monero
- [x] monero-gui
- [x] mongodb
- [x] mongoose
- [x] mongo-tools
- [x] monit
- [x] monitoring-plugins
- [x] mosh
- [x] mosquitto
- [x] mpop
- [x] msmtp
- [x] mtree
- [x] mtxclient
- [x] muchsync
- [x] mumble
- [x] munge
- [x] mutt
- [x] mysql
- [x] namecoin
- [x] neomutt
- [x] neon
- [x] netpgp
- [x] net-snmp
- [x] netsurf
- [x] network-ups-tools
- [x] nginx
- [x] ngircd
- [x] nheko
- [x] nix
- [x] nmap
- [x] nmh
- [x] nrpe
- [x] nsd
- [x] ntp
- [x] nzbget
- [x] opendkim
- [x] open-isns
- [x] openldap
- [x] openntpd
- [x] opensc
- [x] opensmtpd
- [x] openssh
- [x] open-vm-tools
- [x] openvpn
- [x] openvswitch
- [x] opusfile
- [x] pam_ssh
- [x] partclone
- [x] pen
- [x] perl-Crypt-OpenSSL-Bignum
- [x] perl-Crypt-OpenSSL-Random
- [x] perl-Crypt-OpenSSL-RSA
- [x] perl-DBD-mysql
- [x] perl-Net-SSH2
- [x] perl-Net-SSLeay
- [x] pev
- [x] pgadmin3
- [x] pgbouncer
- [x] phantomjs
- [x] php
- [x] pidgin-sipe
- [x] pijul
- [x] pjproject
- [x] pkcs11-helper
- [x] podofo
- [x] postfix
- [x] postgresql
- [x] ppp
- [x] prosody
- [x] pulseaudio
- [x] python
- [x] python3
- [x] python-cryptography
- [x] python-curl
- [x] python-M2Crypto
- [x] qca
- [x] qca-qt5
- [x] qingy
- [x] qt
- [x] qt5
- [x] qupzilla1
- [x] rdesktop
- [x] rdis-git
- [x] re
- [x] remmina
- [x] retroshare
- [x] rhash
- [x] rng-tools
- [x] rspamd
- [x] rtmpdump
- [x] ruby
- [x] rustup
- [x] s3fs-fuse
- [x] s6-networking
- [x] scrypt
- [x] seafile-libclient
- [x] serf
- [x] sgfutils
- [x] sitecopy
- [x] slrn
- [x] slurm-wlm
- [x] s-nail
- [x] socat
- [x] spice
- [x] spice-gtk
- [x] spiped
- [x] sqlcipher
- [x] squid
- [x] stunnel
- [x] swiften
- [x] swi-prolog
- [x] sylpheed
- [x] synergy
- [x] sysdig
- [x] taizen
- [x] tcpdump
- [x] tcpflow
- [x] tectonic
- [x] telegram-desktop
- [x] telepathy-salut
- [x] thc-hydra
- [x] tinc
- [x] tlsdate
- [x] tnftp
- [x] tor
- [x] tpm-tools
- [x] transmission
- [x] trousers
- [x] ttyd
- [x] tvheadend
- [x] ucspi-ssl
- [x] uftp
- [x] uget
- [x] umurmur
- [x] unbound
- [x] vanitygen
- [x] vboot-utils
- [x] vde2
- [x] virtualbox-ose
- [x] VirtualGL
- [x] virtuoso
- [x] vpn-ws
- [x] vsftpd
- [x] w3m
- [x] warzone2100
- [x] watchman
- [x] wesnoth
- [x] wget
- [x] wpa_supplicant
- [x] wrk
- [x] wvstreams
- [x] x11vnc
- [x] xar
- [x] xarcan
- [x] xbps
- [x] xca
- [x] yara
- [x] ykpivmgr
- [x] ympd
- [x] zbackup
- [x] zchunk
- [x] znc
- [x] zou

**Comment by jnbr** [comment]
The largest part of the bumps is done. Reminding ones, besides kernels, are:

- fractal: fails to build
- kicad: fails to build with our version of glm (g-truc/glm#832)
- nheko: to be removed https://github.com/void-linux/void-packages/pull/4372
- pijul: uses incompatible version of rust crate openssl-sys, a patched version of that crate is here: https://github.com/jnbr/rust-openssl/tree/sys-0.9.28-libressl-2.8 , but I didn't figure out how to convince cargo to use this patched version

**Comment by 7185** [comment]
Nice work! I don't know how we're supposed to deal with dependencies of dependencies, but I had to rebuild rtorrent in order to make it work again and I think it might be because of the libtorrent rebuild.

**Comment by jnbr** [comment]
Yes, this was caused by the libtorrent rebuild. Apparently, the rebuild changed the ABI of libtorrent. This shouldn't and usually doesn't happen without a soname bump. This is why we usually don't have to deal with dependencies of libraries we rebuilt.

I don't know of a method to prevent these kind of breakages except doing more testing.
