### ISSUE TITLE
[tracking]: List of currently failing python3 checks

### ISSUE THREAD

**Issue by paper42** [void-linux/void-packages#46170]
builds were done for x86_64-musl on all packages with `build_style=python3-{module,pep517}`. Because of the number of failures (~1/3 of packages without make_check=no), I propose adding `make_check=no` without a comment automatically to every package with failing tests. `make_check=no` without a comment will fail xlint, so the next person touching the package will be encouraged to look into why tests don't work and fix them or add a comment about why they fail.

- [ ] python3-uvloop - tests seem to get stuck
- [ ] guake - vsed in do_check fails
- [x] python3-testscenarios - invalid dependency in `$checkdepends`

## other failures
- [ ] attic
- [ ] awsume
- [x] bCNC
- [ ] beancount
- [ ] canto-curses
- [ ] canto-next
- [ ] clearine
- [ ] coccigrep
- [ ] configshell-fb
- [ ] coursera-dl
- [x] cpuset https://github.com/void-linux/void-packages/pull/51723 
- [ ] curseradio
- [ ] diffoscope
- [x] duplicity
- [ ] edx-dl
- [ ] eyeD3
- [ ] fierce
- [ ] flowblade
- [ ] GCP-Guest-Environment
- [ ] git-review
- [ ] gns3-net-converter
- [ ] Grammalecte
- [x] greg
- [ ] hatch
- [x] hg-git
- [ ] impacket
- [ ] kapidox
- [ ] khal
- [ ] mate-menu
- [ ] mercurial
- [ ] mirage
- [ ] mopidy
- [ ] mopidy-local
- [ ] mopidy-mpd
- [ ] mopidy-multisonic
- [ ] mpd-sima
- [ ] multibootusb
- [ ] neovim-remote
- [ ] nicotine+
- [ ] OpenLP
- [ ] pelican
- [ ] persepolis
- [ ] poezio
- [ ] puddletag
- [ ] pycp
- [ ] PyInstaller
- [ ] pyliblo
- [ ] python3-3to2
- [ ] python3-adblock
- [ ] python3-aiodns
- [ ] python3-aioinflux
- [ ] python3-aionotify
- [ ] python3-alabaster
- [ ] python3-ansiwrap
- [ ] python3-anytree
- [ ] python3-applib
- [ ] python3-argh
- [ ] python3-argon2
- [ ] python3-asn1crypto
- [ ] python3-astral
- [ ] python3-async-timeout
- [ ] python3-async_generator
- [ ] python3-axolotl
- [ ] python3-bibtexparser
- [ ] python3-bitarray
- [ ] python3-bitbucket-api
- [ ] python3-blessings
- [ ] python3-boltons
- [ ] python3-boto3
- [ ] python3-botocore
- [ ] python3-Bottleneck
- [ ] python3-bsddb3
- [ ] python3-casttube
- [ ] python3-cffi
- [ ] python3-changelogs
- [ ] python3-Cheroot
- [ ] python3-chromecast
- [ ] python3-cli-ui
- [ ] python3-colored-traceback
- [ ] python3-ConfigArgParse
- [ ] python3-cram
- [ ] python3-curio
- [ ] python3-curl
- [ ] python3-dbusmock
- [ ] python3-discogs_client
- [ ] python3-dnspython
- [ ] python3-dnsrecon
- [ ] python3-dockerpty
- [ ] python3-dogpile.cache
- [ ] python3-EasyProcess
- [ ] python3-ecdsa
- [ ] python3-eliot
- [ ] python3-enchant
- [ ] python3-enrich
- [ ] python3-envdir
- [ ] python3-enzyme
- [ ] python3-ewmh
- [ ] python3-feedgenerator
- [ ] python3-ffmpeg-python
- [ ] python3-fishnet
- [ ] python3-Flask-Assets
- [ ] python3-Flask-Babel
- [ ] python3-Flask-Mail
- [ ] python3-Flask-OAuthlib
- [ ] python3-Flask-RESTful
- [ ] python3-Flask-Script
- [ ] python3-Flask-WTF
- [ ] python3-furl
- [ ] python3-future
- [ ] python3-fuzzyfinder
- [ ] python3-geojson
- [ ] python3-gevent
- [ ] python3-gmpy2
- [ ] python3-gntp
- [ ] python3-gpg
- [ ] python3-h2
- [ ] python3-habanero
- [ ] python3-hiredis
- [ ] python3-hkdf
- [ ] python3-html2text
- [ ] python3-httpbin
- [ ] python3-httpcore
- [ ] python3-i3ipc
- [ ] python3-ifaddr
- [ ] python3-Inflector
- [ ] python3-influxdb
- [ ] python3-intervaltree
- [ ] python3-iptools
- [ ] python3-ipython_genutils
- [ ] python3-irc
- [ ] python3-itunespy
- [ ] python3-janus
- [ ] python3-jaraco.context
- [ ] python3-jaraco.text
- [ ] python3-jedi
- [ ] python3-Jinja2
- [ ] python3-joblib
- [ ] python3-josepy
- [ ] python3-jsonrpclib
- [ ] python3-jupyter_ipywidgets
- [ ] python3-jupyter_nbconvert
- [ ] python3-jupyter_nbformat
- [ ] python3-jupyter_qtconsole
- [ ] python3-jupyter_widgetsnbextension
- [ ] python3-kaptan
- [ ] python3-keyrings-alt
- [ ] python3-ldap3
- [ ] python3-lsp-server
- [ ] python3-lz4
- [ ] python3-M2Crypto
- [ ] python3-macaroons
- [ ] python3-macholib
- [ ] python3-magic
- [ ] python3-Markups
- [ ] python3-mechanize
- [ ] python3-mediafile
- [ ] python3-mistune
- [ ] python3-mygpoclient
- [ ] python3-namedlist
- [ ] python3-natsort
- [ ] python3-ndg_httpsclient
- [ ] python3-netaddr
- [ ] python3-nose2
- [ ] python3-notify2
- [ ] python3-npyscreen
- [ ] python3-ntlm-auth
- [ ] python3-ntplib
- [ ] python3-oauth2client
- [ ] python3-oauthlib
- [ ] python3-oletools
- [ ] python3-orderedmultidict
- [ ] python3-owm
- [ ] python3-parsedatetime
- [ ] python3-path
- [ ] python3-pbkdf2
- [ ] python3-pbr
- [ ] python3-pcodedmp
- [ ] python3-pdfrw
- [ ] python3-pefile
- [ ] python3-pem
- [ ] python3-pendulum
- [ ] python3-perf
- [ ] python3-pexpect
- [ ] python3-pgmigrate
- [ ] python3-picamera
- [ ] python3-pmw
- [ ] python3-portend
- [ ] python3-prctl
- [ ] python3-precis-i18n
- [ ] python3-puremagic
- [ ] python3-py
- [ ] python3-PyBrowserID
- [ ] python3-pycdio
- [ ] python3-pycodestyle
- [ ] python3-pydbus
- [ ] python3-pyelftools
- [ ] python3-pyfavicon
- [ ] python3-pyflakes
- [ ] python3-PyFxA
- [ ] python3-PyHamcrest
- [ ] python3-pyinfra
- [ ] python3-pykka
- [ ] python3-pylibgen
- [ ] python3-PyOpenGL
- [ ] python3-pypandoc
- [ ] python3-pypdf
- [ ] python3-pyqtgraph
- [ ] python3-pyrfc3339
- [ ] python3-Pyro4
- [ ] python3-pyscss
- [ ] python3-pysdl2
- [ ] python3-pysocks
- [ ] python3-pysrt
- [ ] python3-pytaglib
- [ ] python3-pytest-cov
- [ ] python3-pytest-flake8
- [ ] python3-pytest-xdist
- [ ] python3-pytzdata
- [ ] python3-pywinrm
- [ ] python3-pywt
- [ ] python3-pyx
- [ ] python3-qrcode
- [ ] python3-QtPy
- [ ] python3-random2
- [ ] python3-rarfile
- [ ] python3-raven
- [ ] python3-recommonmark
- [ ] python3-repoze.sphinx.autointerface
- [ ] python3-requests-file
- [ ] python3-requests-mock
- [ ] python3-requests-oauthlib
- [ ] python3-ripe-atlas-cousteau
- [ ] python3-ripe-atlas-sagan
- [ ] python3-rsa
- [ ] python3-rx
- [ ] python3-scikit-video
- [ ] python3-scour
- [ ] python3-scruffy
- [ ] python3-sgmllib
- [ ] python3-sh
- [ ] python3-shodan
- [ ] python3-slixmpp
- [ ] python3-socketIO-client
- [ ] python3-SoCo
- [ ] python3-spake2
- [ ] python3-sphinx-automodapi
- [ ] python3-sphinx_rtd_theme
- [ ] python3-sphinxcontrib-devhelp
- [ ] python3-sphinxcontrib-jsmath
- [ ] python3-sphinxcontrib-qthelp
- [ ] python3-SQLAlchemy2
- [ ] python3-stem
- [ ] python3-stevedore
- [ ] python3-stormssh
- [ ] python3-tables
- [ ] python3-terminaltables
- [ ] python3-testtools
- [ ] python3-tldextract
- [ ] python3-toml
- [ ] python3-trimesh
- [ ] python3-typeguard
- [ ] python3-unittest-mixins
- [ ] python3-urbandict
- [ ] python3-urlgrabber
- [ ] python3-urllib3
- [ ] python3-urwid
- [ ] python3-validators
- [ ] python3-virustotal-api
- [ ] python3-vispy
- [ ] python3-vobject
- [ ] python3-voluptuous
- [ ] python3-waitress
- [ ] python3-watchdog
- [ ] python3-wcmatch
- [ ] python3-webassets
- [ ] python3-Whoosh
- [ ] python3-wikipedia
- [ ] python3-wsproto
- [ ] python3-yarl
- [ ] python3-zc.lockfile
- [ ] python3-zipstream
- [ ] python3-zope.configuration
- [ ] python3-zope.copy
- [ ] python3-zope.deferredimport
- [ ] python3-zope.exceptions
- [ ] python3-zope.i18nmessageid
- [ ] python3-zope.location
- [ ] python3-zope.schema
- [ ] python3-zope.security
- [ ] python3-zope.testing
- [ ] python3-zope.testrunner
- [ ] pywal
- [ ] qomui
- [ ] radicale
- [x] ranger
- [ ] reuse
- [ ] ripe-atlas-tools
- [ ] safeeyes
- [ ] scapy
- [ ] stcgal
- [ ] telepresence
- [ ] tryton
- [x] tuimoji
- [ ] tuir
- [ ] vidcutter
- [ ] vimiv
- [x] virt-manager
- [ ] virtualenvwrapper
- [ ] voltron
- [x] wfuzz
- [ ] whipper
- [x] wpgtk - fixed 0e0d44a7b6247842fad2dfec72386e0db1e62e0d
- [ ] wxPython4
- [x] xdot - fixed 944c72813c231d982e652df4440370f089a1e860
- [x] xkcdpass - fixed 588190a38d467e15ea7fbf7493eca68c7d5af1f5
- [x] xonsh - tests disabled a84e8a4aacaca7d9295289ee6499b1a24864ec2a
- [ ] you-get

**Comment by tornaria** [comment]
python3-gmpy2 fixed in #46192, an actual bug surfaced after the update to mpfr-4.2.1, thanks for the report.

**Comment by Requion** [comment]
Created #46288 with my analysis on Guake.

**Comment by Luciogi** [comment]
Hi, Can I run tests locally ?
