### ISSUE TITLE
[RFC] unvendor desktop files, icons, and similar files from the srcpkgs tree

### ISSUE THREAD

**Issue by classabbyamp** [void-linux/void-packages#49164]
there are a number of packages that include void-created `.desktop` files, icons, and sometimes even other things like manual pages in `srcpkgs/<pkg>/files/`, when files like this should come from upstream or not at all. In a quick survey I did in the past, some of the vendored desktop files even have upstream-provided ones available! (in those cases, the desktop files we have are often outdated or different from upstream)

A rough count finds:
- 91 `.desktop` files (a few should stay, like pipewire's)
- 43 PNG, 2 xpm, and 2 SVG icons

IMO, most, if not all, of these should be removed and either replaced with an existing upstream one or contributed upstream. I'd be interested in working on that if it is desired.

It would also be nice to add some kind of lint for the future to prevent these from slipping in again, as I see it often in new package PRs.

@void-linux/pkg-committers thoughts?

- [x] Maelstrom
- [ ] OpenJK - may need to upstream
- [x] PrusaSlicer
- [ ] QSyncthingTray - abandoned upstream
- [ ] Rocket.Chat-Desktop
- [x] Signal-Desktop
- [ ] SweetHome3D
- [x] WindowMaker
- [x] XyGrib
- [ ] Z80Explorer
- [x] android-studio
- [x] apache-directory-studio-bin
- [x] arduino
- [x] astromenace
- [x] blobby2
- [x] boinc
- [ ] boswars - https://codeberg.org/boswars/boswars/pulls/43
- [ ] caph
- [ ] cavestory
- [x] chatty
- [ ] clipgrab
- [ ] darkplaces
- [ ] dbeaver
- [ ] doom3
- [ ] dosbox
- [ ] dot-xsession
- [ ] dwm
- [ ] eclipse
- [ ] element-desktop
- [ ] evilwm
- [ ] fluxbox
- [ ] freeplane
- [ ] freerouting
- [ ] fsv
- [ ] gnurobbo
- [ ] godot
- [ ] gtkedit
- [ ] imagescan
- [ ] intellij-idea-community-edition
- [ ] jmol
- [ ] jwm
- [ ] kickshaw
- [ ] lbreakout2
- [ ] marvin
- [ ] maxima
- [ ] mplayer
- [ ] mupdf
- [ ] netsurf
- [ ] opensonic
- [ ] pa-applet
- [ ] pingus
- [ ] pipenightdreams
- [ ] polkit-gnome
- [ ] pycharm-community
- [ ] pymol
- [ ] python-tkinter
- [ ] python3-tkinter
- [ ] qt5
- [x] quakespasm - #52045
- [ ] quimup
- [ ] rocksndiamonds
- [ ] rox
- [x] runelite-launcher
- [ ] rxvt-unicode
- [ ] scid_vs_pc
- [ ] sopwith
- [ ] teamspeak3
- [ ] tesseract
- [ ] thunderbird
- [ ] urbanterror
- [ ] vapoursynth-editor
- [ ] vkQuake
- [ ] warsow
- [ ] wm2
- [ ] wmderland
- [ ] wmx
- [x] xdemineur
- [ ] xnec2c
- [x] xonotic - #51975
- [ ] yquake2
- [ ] zsnes

**Comment by classabbyamp** [comment]
- [x] Maelstrom
- [ ] OpenJK
- [ ] PrusaSlicer
- [ ] QSyncthingTray
- [ ] Rocket.Chat-Desktop
- [ ] Signal-Desktop
- [ ] SweetHome3D
- [ ] WindowMaker
- [ ] XyGrib
- [ ] Z80Explorer
- [ ] android-studio
- [ ] apache-directory-studio-bin
- [ ] arduino
- [ ] astromenace
- [ ] blobby2
- [ ] boinc
- [ ] boswars
- [ ] caph
- [ ] cavestory
- [ ] chatty
- [ ] clipgrab
- [ ] darkplaces
- [ ] dbeaver
- [ ] doom3
- [ ] dosbox
- [ ] dot-xsession
- [ ] dwm
- [ ] eclipse
- [ ] element-desktop
- [ ] evilwm
- [ ] fluxbox
- [ ] freeplane
- [ ] freerouting
- [ ] fsv
- [ ] gnurobbo
- [ ] godot
- [ ] gtkedit
- [ ] imagescan
- [ ] intellij-idea-community-edition
- [ ] jmol
- [ ] jwm
- [ ] kickshaw
- [ ] lbreakout2
- [ ] marvin
- [ ] maxima
- [ ] mplayer
- [ ] mupdf
- [ ] netsurf
- [ ] opensonic
- [ ] pa-applet
- [ ] pingus
- [ ] pipenightdreams
- [ ] pipewire
- [ ] polkit-gnome
- [ ] pycharm-community
- [ ] pymol
- [ ] python-tkinter
- [ ] python3-tkinter
- [ ] qt5
- [ ] quakespasm
- [ ] quimup
- [ ] rocksndiamonds
- [ ] rox
- [ ] runelite-launcher
- [ ] rxvt-unicode
- [ ] scid_vs_pc
- [ ] sopwith
- [ ] teamspeak3
- [ ] tesseract
- [ ] thunderbird
- [ ] urbanterror
- [ ] vapoursynth-editor
- [ ] vkQuake
- [ ] warsow
- [ ] wireplumber
- [ ] wm2
- [ ] wmderland
- [ ] wmx
- [ ] xdemineur
- [ ] xnec2c
- [ ] xonotic
- [ ] yquake2
- [ ] zsnes

**Comment by vincele** [comment]
I've searched for dwm upstream's .desktop file and not found anything, c.f.: [here](https://git.suckless.org/dwm/files.html)
