### ISSUE TITLE
[tracking] ffmpeg migration

### ISSUE THREAD

**Issue by classabbyamp** [void-linux/void-packages#51522]
thanks to the various PRs by @zlice, we're close to finishing updating ffmpeg.

This is what remains:

- [ ] audacity - #50047 or #51407
- [ ] electron19
- [ ] electron24
- [ ] qt5-webengine
- [ ] qt6-pdf
- [ ] mediastreamer - linphone links are dead, changed to github belladonne. 5.3.63 does not use ffmepg5+ still
- [ ] moc
- [ ] olive - has been in alpha since 2020, seems they do nightly builds and appimages
- [ ] tvheadend - still no 4.4 release, the 4.3 'dev' works
- [ ] vlc -  vlc4 will support ffmpeg5, there's a patch to build 3.x with ffmpeg5 but it will lack vaapi

**Comment by zlice** [comment]
so i think this broke ffmpeg4 https://github.com/void-linux/void-packages/commit/f1b17547d3fe8ae776a49c28593f87988f676374 - complains it can't find nvidia `ERROR: nvenc requested but not found`

**Comment by zlice** [comment]
also, to get rid of 4, may want to use w/e ffmpeg qt packages instead of system https://github.com/void-linux/void-packages/pull/53844#issuecomment-2575279740

**Comment by METhOphetamine** [comment]
I might be spitting nonsense but aren't you missing some libav* libraries' reverse dependencies on the list? I'm talking about `ppsspp` and `rsgain`. Not sure about `qtav`.

**Comment by zlice** [comment]
hm those both have 4 still...rsgain is not ringing any bells but i swore ppsspp was moved to 6.

**Comment by zlice** [comment]
`kew` is new too, using 4 https://github.com/void-linux/void-packages/blob/master/srcpkgs/kew/template

**Comment by zlice** [comment]
https://github.com/void-linux/void-packages/commit/59fd9d1fc2700f824774a0fa17852b1c5cabdb31 \*sigh* 6 actually breaks ppsspp

https://github.com/hrydgard/ppsspp/issues/15308#issuecomment-1925960243 a comment about not relying on ffmpeg as much

`kew` and `rsgain` should be tested a bit then if moved to 6. guessing 4 will still be around a bit because of vlc anyway

**Comment by METhOphetamine** [comment]
> [59fd9d1](https://github.com/void-linux/void-packages/commit/59fd9d1fc2700f824774a0fa17852b1c5cabdb31) *sigh* 6 actually breaks ppsspp

Wouldn't it be best to use their bundled FFmpeg then? Or I guess FFmpeg 4 could be changed so that it no longer conflicts with the other FFmpeg versions. But then you'd have to change all their `#include`s and their build to point to the older version.

Edit: On a second thought, they do have an official flatpak, so it might be better to just remove the package than package software that will bundle dependencies anyways.

**Comment by zlice** [comment]
both of these build fine with ffmpeg6

kew ffmpeg6 - https://github.com/void-linux/void-packages/pull/56024

rsgain ffmpeg6 - https://github.com/void-linux/void-packages/pull/56023
