### ISSUE TITLE
[TRACKING] Setting up directories in runit services vs. xbps INSTALL/hooks

### ISSUE THREAD

**Issue by Duncaen** [void-linux/void-packages#660]
There is no policy or standard for the preferred method to create certain directories and permissions.

I personally think its better to setup permissions once using `make_dirs` or the `INSTALL` script.
First reason is that if the service fails and the run script runs every second its just a waste of time.
Second reason is that if the admin changes some permissions some services tend to just blindly recursively `chown` or `chmod` directories making it impossible to setup different permissions without
changing the run script.

Directories on `tmpfs` are an exception.

https://github.com/void-linux/void-packages/pull/571
https://github.com/void-linux/void-packages/pull/5

**Comment by pullmoll** [comment]
I agree with @Duncaen here. We have so many policies regarding templates etc. yet the way how required directories, permissions and ownership is established varies very much.

**Comment by Gottox** [comment]
Okay. Can somebody create a list of affected packages? - We can turn #660 into a tracking issue.

**Comment by Duncaen** [comment]
- [ ] srcpkgs/munge/files/munge/run:chown munge:munge /var/lib/munge
- [ ] srcpkgs/zabbix/files/zabbix-agent/run:chown _zabbix_agent:_zabbix_agent /var/run/zabbix-agent /var/log/zabbix-agent
- [ ] srcpkgs/zabbix/files/zabbix-proxy/run:chown _zabbix_proxy:_zabbix_proxy /var/run/zabbix-proxy /var/log/zabbix-proxy
- [ ] srcpkgs/zabbix/files/zabbix-server/run:chown _zabbix_server:_zabbix_server /var/run/zabbix-server /var/log/zabbix-server
- [ ] srcpkgs/boinc/files/boinc/run:chown --recursive ${BOINCUSER}:${BOINCUSER} ${BOINCDIR} ${LOGFILE} ${ERRORLOG}
- [ ] srcpkgs/puppet/files/puppetmaster/run:chown -R puppet:puppet /var/lib/puppet
- [ ] srcpkgs/sickbeard/files/sickbeard/run:    chown sickbeard:sickbeard /var/lib/sickbeard
- [ ] srcpkgs/bitlbee/files/bitlbee/run:chown bitlbee:bitlbee /var/lib/bitlbee /run/bitlbee
- [ ] srcpkgs/deluge/files/deluged/run:chown deluge:deluge /var/lib/deluge
- [ ] srcpkgs/inadyn/files/inadyn/run:chown inadyn:inadyn /run/inadyn /var/cache/inadyn
- [ ] srcpkgs/postgresql/files/postgresql/run:  chown -R postgres:postgres "$PGDATA"
- [ ] srcpkgs/minio/files/minio/run:chown -R  _minio:_minio $MINIO_VOLUMES
- [ ] srcpkgs/lighttpd/files/lighttpd/run:  chown _lighttpd:_lighttpd $ROOTDIR
- [ ] srcpkgs/lighttpd/files/lighttpd/run:  chown _lighttpd:_lighttpd $LOGDIR
- [ ] srcpkgs/redis/files/redis/run:chown redis:redis /var/lib/redis
- [ ] srcpkgs/clockspeed/files/clockspeed_adjust/run:chown clocksd /var/lib/clockspeed/adjust
- [ ] srcpkgs/monkey/files/monkey/run:  chown _monkey:_monkey $ROOTDIR
- [ ] srcpkgs/monkey/files/monkey/run:  chown _monkey:_monkey -R $LOGDIR
- [ ] srcpkgs/couchpotato/files/couchpotato/run:    chown couchpotato:couchpotato /var/log/couchpotato.log
- [ ] srcpkgs/suricata/files/suricata/run:chown -R suricata:suricata /var/lib/suricata /var/log/suricata
- [ ] srcpkgs/gogs/files/gogs/run:  chown ${USER}:${GROUP} $f
- [ ] srcpkgs/apache/files/apache/run:  chown _apache:_apache $ROOTDIR
- [ ] srcpkgs/apache/files/apache/run:  chown _apache:_apache $LOGDIR
- [ ] srcpkgs/bluez-alsa/files/bluez-alsa/run:[ ! -d "${dir}" ] && mkdir "${dir}" && chown $user:$group ${dir}
- [ ] srcpkgs/h2o/files/h2o/run:chown h2o:h2o $LOGDIR
- [ ] srcpkgs/sddm/files/sddm/run:chown -R sddm:sddm /var/lib/sddm
- [ ] srcpkgs/caddy/files/caddy/run:chown caddy:caddy "$CADDYPATH"
- [ ] srcpkgs/mpd/files/mpd/run:chown -R mpd:mpd /var/lib/mpd
- [ ] srcpkgs/netdata/files/netdata/run:    chown -R _netdata:_netdata /var/${f}/netdata
- [ ] srcpkgs/kapacitor/files/kapacitor/run:chown -R _kapacitor:_kapacitor /var/log/kapacitor
- [ ] srcpkgs/i2pd/files/i2pd/run:    chown -R  _i2pd:_i2pd /var/lib/i2pd
- [ ] srcpkgs/preload/files/preload/log/run:    chown -R $user_group "/var/log/$logdir"
- [ ] srcpkgs/PopCorn/files/popcorn/run:chown -R _popcorn:_popcorn /etc/popcorn
- [ ] srcpkgs/quassel/files/quasselcore/run:            chown -R quassel:quassel /var/${dir}/quassel &&
- [ ] srcpkgs/trousers/files/tcsd/run:[ -d /var/lib/tpm ] || install -m 0700 -o tss -g tss -d /var/lib/tpm
- [ ] srcpkgs/tinyproxy/files/tinyproxy/run:install -d -m 0755 -o _tinyproxy -g _tinyproxy \
- [ ] srcpkgs/rspamd/files/rspamd/run:      install -d -m 0755 -o $RSPAMDUSER -g $RSPAMDGROUP $dir
- [ ] srcpkgs/beanstalkd/files/beanstalkd/run:[ -d /var/lib/beanstalkd ] || install -D -o beanstalkd -g beanstalkd /var/lib/beanstalkd
- [ ] srcpkgs/mpd/files/mpd/run:install -d -m 0755 /var/lib/mpd/playlists

**Comment by Gottox** [comment]
* [ ] srcpkgs/NetworkManager/files/NetworkManager/run:[ ! -d /etc/NetworkManager/dispatcher.d ] && mkdir -m0755 -p /etc/NetworkManager/dispatcher.d

**Comment by CameronNemo** [comment]
Do we really need to check for existence first? `install` won't replace files that already exist, it will just change the permissions.

**Comment by maxice8** [comment]
minio uses /etc/default/minio instead of a simple conf file.

**Comment by maxice8** [comment]
Apache is fixed

**Comment by sgn** [comment]
- [ ] srcpkgs/bro/files/bro/run:7:[ -d ${BROLOGDIR} ] || mkdir -p ${BROLOGDIR}
- [ ] srcpkgs/clockspeed/files/clockspeed/run:5:[ -d /var/lib/clockspeed/etc ] || mkdir -p /var/lib/clockspeed/etc
- [ ] srcpkgs/dnsmasq/files/dnsmasq/run:2:mkdir -p /var/lib/misc
- [ ] srcpkgs/docker/files/docker/run:5:    mkdir -p /sys/fs/cgroup/systemd;
- [ ] srcpkgs/sklogw/files/sklogw/log/run:4:[ -d /var/log/sklogw ] || mkdir -p /var/log/sklogw
- [ ] srcpkgs/twoftpd/files/twoftpd-anon/run:6:mkdir -p $(<./env/HOME)
- [ ] srcpkgs/xen/files/xenconsoled/run:3:mkdir -p /var/log/xen/console

snooze also have this `mkdir -p`, but it's shipped by upstream.

**Comment by CameronNemo** [comment]
/sys/fs/cgroup is a tmpfs, so docker is fine.

**Comment by sgn** [comment]
> /sys/fs/cgroup is a tmpfs, so docker is fine.

OK, my filter missed that, I filtered out `/run` and `/var/run`
